#version 430 core
layout(local_size_x=16, local_size_y=16) in;

layout(rg32f,binding=0) readonly uniform image2D spectrumH;

layout(r32f, binding=1) writeonly uniform image2D uWaveTex;

uniform float domainSize;

void main()
{
    ivec2 gid= ivec2(gl_GlobalInvocationID.xy);
    ivec2 sz= imageSize(spectrumH);
    if(gid.x>=sz.x||gid.y>=sz.y) return;

    vec4 c= imageLoad(spectrumH,gid);
    float hVal= c.r;  // imag part c.g== 0 ?

    imageStore(uWaveTex, gid, vec4(hVal,0,0,0));
}
